### ISSUE TITLE
Serial.readline blocks with Arduno Zero

### ISSUE THREAD

**Issue by louisvangeldrop** [Microsoft/pxt-maker#118]
**Describe the bug**
serial.readString() blocks after entering a character.

Example Code:

serial.setBaudRate(BaudRate.BaudRate115200)
serial.attachToConsole()

forever(function () {
    pause(300)
    let data = serial.readString()
    console.log(data)
    serial.writeString(data)
})

**Comment by sabas1080** [comment]
for the moment serial only works on pad 0 of the sercom

**Comment by louisvangeldrop** [comment]
Also no results at pad 0

**Comment by sabas1080** [comment]
pad 0 of which sercom?

**Comment by louisvangeldrop** [comment]
The RX pin = D0 on the Zero. At the pc it is connected to com8 over USB using a usb ttl converter
