### ISSUE TITLE
Keyboard blocks cannot accept variable

### ISSUE THREAD

**Issue by deanm1278** [Microsoft/pxt-maker#12]
Trying to do this doesn't work:
![screenshot 5](https://user-images.githubusercontent.com/6306234/35457281-598cdce6-02a6-11e8-8617-8bd104eb1d1e.png)

I can get it to work in the javascript editor using
```
let item = 0
loops.forever(function () {
    keyboard.type(pins.A0.analogRead().toString())
})
```

**Comment by pelikhan** [comment]
Could you click on "share" and paste the program URL?

**Comment by deanm1278** [comment]
https://makecode.com/_H3p3r5VFk8ua

**Comment by pelikhan** [comment]
Right, this block only accepts a string and don't auto convert numbers to string. Try 

https://makecode.com/_aR38RrhE0APC

**Comment by ladyada** [comment]
that works! but...is super unintuitive :/
i dont know javascript as much as other langs but maybe we can check the type and print out the 'displayable' version? Arduino Serial.print() and python print() do what you expect :)

**Comment by pelikhan** [comment]
@riknoll could we have an automatic conversion from number to string in blocks?

**Comment by pelikhan** [comment]
Fixed.
