### ISSUE TITLE
slide switches UI bug on HID mouse button block

### ISSUE THREAD

**Issue by deanm1278** [Microsoft/pxt-maker#13]
clicking the slide switch for the first time results in confusing UI
![screenshot 31](https://user-images.githubusercontent.com/6306234/35457777-11ab3344-02a8-11e8-9b36-cdc26d9818d8.png)

the bottom mouse button block is how it appears on first click of the slide swtich. It straightens itself out after clicking it two more times and looks like the top mouse button block

using Chrome on windows 10

**Comment by pelikhan** [comment]
Got the repro, fixing

**Comment by pelikhan** [comment]
Fixed deployed.
