### ISSUE TITLE
WebUSB or console device

### ISSUE THREAD

**Issue by sabas1080** [Microsoft/pxt-maker#149]
**Describe the bug**
In version beta

MakeCode Maker (Cortex class) version:  0.6.4
Microsoft MakeCode version:  5.4.7

webusb only work when device reset in mode boot and download firmware. previously pair from the menu configuration

**To Reproduce**
1. Pair device
2. Download firmware with console.log include and never ends
3. Reset device with double boton click, enter in mode boot and download firmware

My code

```
forever(function () {
    console.logValue("value", input.touchA0.value())
})
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 71

**Additional context**
tested in mrk1300 and meow meow

**Comment by pelikhan** [comment]
Could add the code snippet you are using?

**Comment by sabas1080** [comment]
ready

**Comment by pelikhan** [comment]
Console fixed.
