### ISSUE TITLE
No mapping on Trinket M0 A1/D2 pins with LIGHT in Maker

### ISSUE THREAD

**Issue by FrankSchmidtDDS** [Microsoft/pxt-maker#159]
**Describe the bug**
An error in simulator Fritizing diagram when using LIGHT function in the Adafruit Trinket M0 board.

**To Reproduce**
1. Go to '...
https://makecode.com/_auYiA34yD9ap
'
2. Click on '...Edit.'
3. Click on "Simulator" 

**Expected behavior**
You should see 3 wires in the diagram (and you do if pins other than A1/D2 are chosen) ; there should be a wire to ground, to voltage and a third wire to the pin A1/D1 and the signal pad on the light strip.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser [e.g. chrome, Internet Explorer and Bing)
![20190126_113437](https://user-images.githubusercontent.com/37808678/51914306-2a1f2580-239e-11e9-9428-50d6deb02dcf.jpg)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pelikhan** [comment]
Fixed.
