### ISSUE TITLE
RedBoard Turbo w/ External Addressable LEDs

### ISSUE THREAD

**Issue by bboyho** [Microsoft/pxt-maker#188]
**Describe the bug**
Adding an external WS2812-based LEDs from the "Light" blocks seems to not fully work on other pins when using it with the SparkFun RedBoard Turbo under MakeCode Beta site. There seems to be issues controlling LEDs after 3 or 4 pixels. There also seems to be issues setting up all the LEDs to the same color. The on-board WS2812B stays lit with the color green even when not calling it.

Maybe I am setting it up incorrectly?

**To Reproduce**
1. Connect external WS2812s to A1, 3.3V, and GND.
2. Drag the `Light > More > set strip to create WS2812 strip on LED with 30 pixels` code block into the `setup`.
3. Change `LED` to `A1`.
4. Change `30` pixels to `5` pixels.
5. Drag `Light > More > set strip brightness 20` into the `setup`.
6. Change brightness `20` to `150`.
7. Drag the `Light > More > set strip show animation for 500ms` code block into `forever`.
8. Adjust `500` ms to 200` ms.
9. Drag the `Light > More > set strip all pixels to blue` code block into `forever`.
10. Add a few pauses between the animation and setting all LEDs to the same color.

**Expected behavior**
The 5x external WS2812 LEDs should animate and then all change to the color blue.

**Screenshots**
![turbo makecode beta external addressable leds](https://user-images.githubusercontent.com/3209977/53363204-1d3c1600-38f9-11e9-9442-e9ddf6de9fda.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 (64-bit)
 - Browser: 
 - Version:  72.0.3626.109 (Official Build) (64-bit)

**Comment by pelikhan** [comment]
@bboyho you can click on the "share" button and copy the URL generated as well. Or copy paste the image generated by the "save" button.

**Comment by pelikhan** [comment]
The following programs works locally both for A1 and MOSI
```
let on = false;
forever(function () {
    pins.LED.digitalWrite(on = !on)
    pause(100)
});

let strip = light.createNeoPixelStrip(pins.A1, 60)
forever(function () {
    strip.showAnimation(light.rainbowAnimation, 2000)
    strip.setAll(0xff0000)
    pause(500)
    strip.setAll(0x00ff00)
    pause(500)
    strip.setAll(0x0000ff)
    pause(500)
})
light.setLength(60)
forever(function () {
    light.showAnimation(light.rainbowAnimation, 2000)
    light.setAll(0x0000ff)
    pause(2000)
})
```

**Comment by pelikhan** [comment]
Reopen if you have a hardware repro. Video helps.

**Comment by bboyho** [comment]
As a quick note, I tested this with a second set of WS2812 LEDs on a strip and it works. The initial test must have had a bad set of addressable LEDs.  False alarm.

Thanks for your patience. =)

**Comment by pelikhan** [comment]
I also tested a strip of APA102s on the lumidrive — all good. If you mount them on the SPI pin, you’ll get DMA accelerated as well.
