### ISSUE TITLE
RedBoard Turbo w/ Servo Block

### ISSUE THREAD

**Issue by bboyho** [Microsoft/pxt-maker#197]
**Describe the bug**
Issue with the servo blocks. Attaching a servo on the analog pins does not seem to work when using it with the SparkFun RedBoard Turbo under the MakeCode Beta site.

I am not sure if I am doing it correctly?

**To Reproduce**
Servo does not seem to move when it is connected to the analog pins A0-A5.

1. Drag and set `pins > servo write pin A1 to 0` in the forever loop.
2. Drag and set `loops > pause 1000 ms`.
3. Drag and set `pins > servo write pin A1 to 180`.
4. Drag and set  `loops > pause 1000 ms`.

**Expected behavior**
The servo should move between two positions every second on a PWM pin. The example works when the servo is connected to the PWM pins between D3-D13 but it does not work on A0-A5. Looking at the pinout, it does not seem like the RedBoard Turbo has any PWM pins on A0-A5?

**Screenshots**
https://makecode.com/_FPrd0969PMDA

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version:  72.0.3626.109 (Official Build) (64-bit)

**Comment by pelikhan** [comment]
This is the pin definitions. https://github.com/Microsoft/pxt-maker/blob/master/libs/sparkfun-redboard-turbo/device.d.ts

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pelikhan** [comment]
This is where pins are defined: https://github.com/Microsoft/pxt-maker/blob/master/libs/sparkfun-redboard-turbo/device.d.ts

**Comment by pelikhan** [comment]
Fixed by https://github.com/Microsoft/pxt-maker/commit/9028b1974575982e1d65a9dcfb8c35f99b9bb670
