### ISSUE TITLE
Issue using LCD with Adafruit Metro M4

### ISSUE THREAD

**Issue by brentru** [Microsoft/pxt-maker#204]
**Describe the bug**
@pelikhan - I've wired an Adafruit Metro M4 the same way the Metro M4 in the editor window is wired. Then I and added the `LCD Show String` block to print out "hello world". The LCD shows nothing, though it is turned on. This may be an issue where the wiring on the site is incorrect.

**To Reproduce**
1. Go to LCD
2. Click on _LCD Show String "Hello World" at line 1_

**Expected behavior**
LCD should display Hello World.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
As a side-note, the LCD should be connected to the Metro's +5V instead of +3.3V (using this standard 16x2 LCD for reference; https://www.adafruit.com/product/181)

**Comment by pelikhan** [comment]
Could you try using the 5V rail for the large LCD? I need to add support for 5V in our routing algorithm.

**Comment by pelikhan** [comment]
Might be the brightness pin that is incorrect.

**Comment by brentru** [comment]
@pelikhan  I used the 5V rail for the 16x2 LCD when I wired it up on the breadboard. Could you paste the pinouts in here (they're a bit strange on the website, not sure if they're correct)

**Comment by pelikhan** [comment]
I following this guide/pinout for the wiring: https://learn.adafruit.com/experimenters-guide-for-metro/circ14-wiring . The pinout is here: https://github.com/Microsoft/pxt-maker/blob/master/libs/adafruit-metro-m4-express/config.ts#L58

**Comment by pelikhan** [comment]
I was missing the ground wire from RW
![image](https://user-images.githubusercontent.com/4175913/54063796-d2a57e00-41c3-11e9-9803-505bb6212cff.png)

**Comment by pelikhan** [comment]
@brentru please try again (v0,9.16). it routes to 5v and has the missing round wire.
![maker-hello-world](https://user-images.githubusercontent.com/4175913/54064920-6419ed80-41ce-11e9-86a9-72a8381af722.png)

**Comment by pelikhan** [comment]
Fixed.

**Comment by brentru** [comment]
@pelikhan  Thanks for fixing, works on my end.
