### ISSUE TITLE
Remaining TODOs for BFA 2019

### ISSUE THREAD

**Issue by teddyseyed** [microsoft/pxt-maker#224]
### Beads

**JACDAC drivers for Color bead**
- [ ] Detect R G or B for bead. 

**JACDAC drivers for Motion bead**
- [x] Detect shake / be able to tweak shake sensitivity. 

**JACDAC drivers for Proximity bead**
- [x] Complete i2c TS proximity bead driver (close / near / far)
- [x] Translate driver into TS-jacdac driver

**JACDAC drivers for Light bead**
- [x] Detect visible light level for bead. 

**JACDAC drivers for Motor bead**
- [ ] Complete i2c TS motor bead driver (continuous rotate, pan, or tilt) 
- [ ] Translate driver into TS-jacdac driver

### Designer Testing Scenarios

- [ ] Brain + Motion + LED strips
- [ ] Brain + Tattoo + Motor
- [ ] Brain + Tattoo + Motor + LED strips
- [ ] Brain + Tattoo + LED Strips
- [ ] Brain + Proximity + LED Strips
- [ ] Brain + Color Sensor + LED Strips
- [ ] Brain + Light Sensor + LED Strips
- [ ] Brain + Motion + Tattoo + LED Strips

### Extension

- [ ] Name a bead functionality
- [ ] Generate block based on interface planning
- [x] Program tattoo

**Comment by jamesadevine** [comment]
WE ARE DONE WITH THIS!
