### ISSUE TITLE
ItsyBitsy M0 express blink D13 not working

### ISSUE THREAD

**Issue by jedgarpark** [microsoft/pxt-maker#246]
Attempted to blink pin D13 LED from Maker makecode on ItsyBitsy M0 and it doesn't work. Also noted that the image in the simulator is of the M4 board, not the M0.

**Comment by wallarug** [comment]
Hey @jedgarpark  is this still an issue for you?

**Comment by jedgarpark** [comment]
D13 blinks and board image is correct, thanks!
