### ISSUE TITLE
Python indention issues

### ISSUE THREAD

**Issue by gbaman** [microsoft/pxt-maker#265]
**Describe the bug**
When writing code in the Python editor, 2 related issues.

1. When hitting enter after a colon, would expect the following section to be indented.
2. When switching back and forth (see gif) between python/blocks/python, some odd indention can occur...

**To Reproduce**
1. Create a new program with a forever loop and a block with in.
2. Switch to Python view.
3. Select the colon on the function and hit enter.

**Expected behavior**
When the enter key is pressed on a line ending in a colon, it should auto indent the next line.

When converting between blocks and Python, would expect blank lines to be kept and double indenting not to be used?

**Screenshots**
Auto indent on colon issue
![Screen Recording 2019-11-21 at 21 14 52](https://user-images.githubusercontent.com/833193/69377514-5cd73900-0ca4-11ea-8011-88b0a3fffc87.gif)

Python -> Blocks -> Python indentation issue
![Screen Recording 2019-11-21 at 21 12 09](https://user-images.githubusercontent.com/833193/69377564-72e4f980-0ca4-11ea-99c8-4a5f02ad3943.gif)

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser: Firefox
 - Version: 70

**Comment by darzu** [comment]
Thanks for the great repro.

**Comment by darzu** [comment]
We're working on a bunch of Python fixes and improvements as a top priority over the next few months.

**Comment by pelikhan** [comment]
A bunch of fixes are live now.

**Comment by darzu** [comment]
Partially fixed by: https://github.com/microsoft/pxt/pull/6270
not yet integrated into maker; more fixes coming

**Comment by darzu** [comment]
I duped the remaining work issue to: https://github.com/microsoft/pxt-minecraft/issues/1471
since we're first releasing python in Minecraft so I'm tracking key issues there.

**Comment by pelikhan** [comment]
Fixed.
