### ISSUE TITLE
npm run svgo runs for all boards

### ISSUE THREAD

**Issue by wallarug** [microsoft/pxt-maker#274]
Hi There,

When you run step 4 of the docs to minify the board.hd.svg file 

```npm run svgo```

It runs for all the boards in the `libs` folder.  This is an issue for adding new boards as it means every-time someone does a PR, you will get different SVG files (un-necessarily).

Is there a way to run a single board instead of all 34+ boards?

**Comment by pelikhan** [comment]
I've run svgo on all boards and updated the docs. Please pull the changes.
