### ISSUE TITLE
Is there a way to use a private repository for codalTarget?

### ISSUE THREAD

**Issue by OpusK** [microsoft/pxt-maker#279]
Hi, 

Can I use a private repository with codalTarget's git repository?
In [yotta, "git + ssh"](http://docs.yottabuild.org/tutorial/privaterepos.html) seems to play the role, but is there a way to do it in codal?

```json
                "codalTarget": {
                    "name": "codal-nrf52840-dk",
                    "url": "https://github.com/mmoskal/codal-nrf52840-dk",
                    "branch": "v1.1.0",
                    "type": "git"
                },
```

**Comment by pelikhan** [comment]
Is this to build locally or to build in our cloud?

**Comment by OpusK** [comment]
Do the settings differ depending on the build location?
I'm currently building locally.

**Comment by pelikhan** [comment]
Using a terminal with git credentials should work. Cloud build of private repoes require authorization on our part

**Comment by OpusK** [comment]
Thanks, @pelikhan :)
I understood.
