### ISSUE TITLE
How to Change the server port

### ISSUE THREAD

**Issue by Kunal614** [microsoft/pxt-maker#309]
Sir i have to change the port to 8080 , so in which file i have to change this , I make changes in  karma.conf.js 
but also running in 3233 port
![Screenshot from 2020-04-21 11-05-14](https://user-images.githubusercontent.com/43969265/79829161-00498880-83c0-11ea-9205-95d5b502c9af.png)

**Comment by pelikhan** [comment]
pxt serve is not meant to run in the cloud. it is for development purposes only
