### ISSUE TITLE
Share button not working 

### ISSUE THREAD

**Issue by gotfredsen** [microsoft/pxt-maker#311]
Hi,

The Share button 
<img width="436" alt="Screenshot 2020-04-23 at 3 37 25 PM" src="https://user-images.githubusercontent.com/2776277/80105703-39792880-8579-11ea-9d7d-145720d3fe36.png"> 
does not work on our implementation of pxt-maker.

We get the following error, and I can't source the issue:
<img width="1552" alt="Screenshot 2020-04-23 at 3 18 35 PM" src="https://user-images.githubusercontent.com/2776277/80105843-64637c80-8579-11ea-87e9-f97d457e293e.png">

Any help will be appreciated.

**Comment by pelikhan** [comment]
It is only supported for editors hosted by Microsoft. You will have to implement the share api on your backend to support this.

________________________________

**Comment by gotfredsen** [comment]
Ok, Thanks Peli
