### ISSUE TITLE
Enter key for HID keyboard extension

### ISSUE THREAD

**Issue by jedgarpark** [microsoft/pxt-maker#321]
There doesn't seem to be an option for pressing the enter key with HID keyboard extension.

**Comment by pelikhan** [comment]
grrr

**Comment by CHristapherenese** [comment]
Any progress on this issue, really would like to get this project off my to do list and this is holding everything up

**Comment by CHristapherenese** [comment]
Anything..

**Comment by CHristapherenese** [comment]
Looks like it has been added
