### ISSUE TITLE
PWM option for music

### ISSUE THREAD

**Issue by jedgarpark** [Microsoft/pxt-maker#33]
Trying out the music blocks on a Gemma M0 -- works well w a speaker on A0, wonder if there could be an option to configure for PWM when using a piezo?

**Comment by pelikhan** [comment]
Not yet but that should be something that could be added. So basically you would specify another pin for the music output, is that correct? (A0 does ADC, not PWM).

**Comment by pelikhan** [comment]
@mmoskal did some work around ``music---pwm`` . I'll sync with him.

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-maker/commit/ad1e46391fdea837b9cc62b3fb2d99aeda48b91d
