### ISSUE TITLE
SPI support ?

### ISSUE THREAD

**Issue by sabas1080** [Microsoft/pxt-maker#47]
Hi

I am testing with a sparkfun dev board

I want to try an SPI sensor, but I do not see any examples

I tried with

`spiPins(mosi: DigitalPin, miso: DigitalPin, sck: DigitalPin)`

but it does not look like a valid command

Thanks

**Comment by pelikhan** [comment]
@mmoskal I see CODAL_SPI but I don't think we've exposed a typescript Api for it yet.

**Comment by sabas1080** [comment]
Is there a plan to do it or approximate date?

**Comment by pelikhan** [comment]
Right, we haven't migrated yet those APIs, but it shouldn't be too hard to add them.

https://github.com/Microsoft/pxt-microbit/blob/master/libs/core/pins.cpp#L385

**Comment by pelikhan** [comment]
Here's the PR
https://github.com/Microsoft/pxt-common-packages/pull/307

**Comment by pelikhan** [comment]
And it's live.

**Comment by sabas1080** [comment]
Thank you very much

**Comment by mmoskal** [comment]
We might be changing transfer API to be full duplex. Best use it with one of the buffers being `null` - this will continue to work as it does now.
