### ISSUE TITLE
Feedback on maker.makecode.com

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt-maker#5]
1. The breadboard blends in with the background. I think it's more clear when there's a distinction:
![image](https://user-images.githubusercontent.com/6453828/35349459-d4110464-00ef-11e8-9d2f-7ea796b08257.png)
vs.
![image](https://user-images.githubusercontent.com/6453828/35349535-092f2ad6-00f0-11e8-9d59-3951f815425b.png)

2. The +/- "zoom" buttons in the bottom right only zoom the blocks. I would have expected them to at least zoom the simulator. The breadboard especially is helpful to zoom since there's a lot of detail there (whereas with the microbit simulator, the detail isn't as small.)

**Comment by darzu** [comment]
Looks better today, thanks!
![image](https://user-images.githubusercontent.com/6453828/35396859-b0c9672c-01a2-11e8-8fe3-5005a9100be1.png)

**Comment by pelikhan** [comment]
Fixed. Zoom is a deeper issue not addressed here.
