### ISSUE TITLE
Blocks serial available and read

### ISSUE THREAD

**Issue by sabas1080** [Microsoft/pxt-maker#64]
Hi @mmoskal 

My intention is to read the information of a device via serial, but I have noticed that the "Serial" package does not have the functions `Serial.available and Serial.read`

Is there any intention to add them?

Thanks

**Comment by pelikhan** [comment]
Can you send a PR?

**Comment by sabas1080** [comment]
Yes, but you can not test because I'm in samd21

**Comment by pelikhan** [comment]
We typically HF2/WebUSB for logging. What are you testing?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sabas1080** [comment]
Communication with an module serial as GPS

**Comment by pelikhan** [comment]
Try again, serial library now available.

**Comment by sabas1080** [comment]
not working serial, my code is:

```
serial.setBaudRate(BaudRate.BaudRate115200)
serial.redirect(pins.TX, pins.RX)
forever(function () {
    pins.LED.digitalWrite(true)
    pause(500)
    pins.LED.digitalWrite(false)
    pause(500)
    console.logValue("x", 0)
})
```

**Comment by pelikhan** [comment]
try ``serial.writeValue("x", 0)``

**Comment by pelikhan** [comment]
Add
```
serial.attachToConsole()
```

**Comment by sabas1080** [comment]
the intermediate blink does not work when serial insert

```
serial.setBaudRate(BaudRate.BaudRate115200)
serial.redirect(pins.TX, pins.RX)
serial.attachToConsole()
forever(function () {
    serial.writeValue("x", 0)
    pins.LED.digitalWrite(true)
    pause(500)
    pins.LED.digitalWrite(false)
    pause(500)
})
```

**Comment by pelikhan** [comment]
Do you have serial working at the CODAL level?

**Comment by sabas1080** [comment]
How can I do that?

**Comment by pelikhan** [comment]
Write a C++ tests that uses your codal target and serial to make sure everything works at that level.

**Comment by pelikhan** [comment]
I will try with a metro tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sabas1080** [comment]
Serial Working, Now I'm going to read
![img_20181106_121103704](https://user-images.githubusercontent.com/2874292/48084484-77379500-e1bd-11e8-8157-a0fbddb0b16f.jpg)

**Comment by pelikhan** [comment]
Looks like this done.
