### ISSUE TITLE
Chrome error visible

### ISSUE THREAD

**Issue by sabas1080** [Microsoft/pxt-maker#80]
Hi

**Describe the bug**

Sometimes it does not load the page correctly and the following errors appear in the console

**Screenshots**
![captura de pantalla 2018-10-27 a la s 18 22 58](https://user-images.githubusercontent.com/2874292/47610319-0bfcfe80-da18-11e8-99ef-7c7e02b10118.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Sierra
 - Browser Chrome
 - Version 70

**Additional context**
In oficial page and local server

Thanks

**Comment by pelikhan** [comment]
Fix on the way, clean the browser cache and it should be fixed.

**Comment by sabas1080** [comment]
Thanks
