### ISSUE TITLE
Not Working Blink in any board

### ISSUE THREAD

**Issue by sabas1080** [Microsoft/pxt-maker#81]
**Describe the bug**
the latest stable and beta web version does not work the blink, it seems the board is broken

**To Reproduce**
Example blink

tested on:
- SAMD21 sparkfun
- Meow Meow
- MKR1300

**Desktop (please complete the following information):**
 - OS: MacOS Sierra and Windows 10
 - Browser Chrome
 - Version 70

**Comment by pelikhan** [comment]
I tested on the metro express m0 without trouble. Can you test that one?

**Comment by pelikhan** [comment]
Which editor version please.

**Comment by pelikhan** [comment]
Actually, try removing the “storage” package.

**Comment by sabas1080** [comment]
Beta (https://maker.makecode.com/beta) and stable (https://maker.makecode.com)

I have not tried locally

**Comment by pelikhan** [comment]
Go to about and add the version number here.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sabas1080** [comment]
MakeCode Maker (Cortex class) version:  0.5.34

Microsoft MakeCode version:  4.3.8

codal-circuit-playground runtime version:  v1.5.3

**Comment by pelikhan** [comment]
Might be the storage package that is messing things up. Will test later.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Will find it in a few mins

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
Looks like there are some updates needed in the mkr1300 target.
```
home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp: In function 'int target_seed_random(uint32_t)':
/home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp:59:12: error: 'seed_random' is not a member of 'codal'
     return codal::seed_random(rand);
            ^~~~~
/home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp: In function 'int target_random(int)':
/home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp:63:12: error: 'random' is not a member of 'codal'
     return codal::random(max);
            ^~~~~
/home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp: In constructor 'codal::MKR1300::MKR1300()':
/home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp:154:49: error: no matching function for call to 'codal::_mbed::Serial::Serial(codal::_mbed::Pin&, codal::_mbed::Pin&)'
     lightSensor(io.light, DEVICE_ID_LIGHT_SENSOR)
                                                 ^
In file included from /home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.h:54:0,
                 from /home/build/prjclone/libraries/codal-mkr1300/model/MKR1300.cpp:26:
/home/build/prjclone/libraries/codal-mbed/inc/MbedSerial.h:193:13: note: candidate: codal::_mbed::Serial::Serial(PinName, PinName, uint8_t, uint8_t)
             Serial(PinName tx, PinName rx, uint8_t rxBufferSize = CODAL_SERIAL_DEFAULT_BUFFER_SIZE, uint8_t txBufferSize = CODAL_SERIAL_DEFAULT_BUFFER_SIZE);
```

**Comment by pelikhan** [comment]
It is still building v0,0,7,

**Comment by sabas1080** [comment]
My version local working
```
                    "url": "https://github.com/ElectronicCats/codal-mkr1300",
                    "branch": "v0.0.7",
```

![captura de pantalla 2018-11-05 a la s 13 48 06](https://user-images.githubusercontent.com/2874292/48022752-91ac3880-e101-11e8-8f3f-8c8d216dd35b.png)

**Comment by sabas1080** [comment]
Are you sure did you change? that error is from past commits

**Comment by pelikhan** [comment]
I've just pushed a change to use docker for all builds. The blinky sseems to download fine for mkr1300 but I do not have a board to test on device.

**Comment by pelikhan** [comment]
Looks like the storage is creating the issue. Fixing.

**Comment by sabas1080** [comment]
All ok, blink again!
